server:
  port: 8762
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations:
            classpath:/config/,
            classpath:/config/client-config-first,
            classpath:/config/client-discovery-first